parameters:
- name: jobName
  type: string
  default: BicepEnvironmentValidation
- name: dependsOn
  type: object
  default: []
- name: azureSubscription
  type: string
- name: environment
  type: string

jobs:
- deployment: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}
  environment: 'platform-monitoring-${{ parameters.environment }}'

  workspace:
    clean: all

  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: RunPreflightValidation
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub validate `
                  --template-file bicep/platform.bicep `
                  --location 'uksouth' `
                  --parameters @params/platform.${{ parameters.environment }}.json

                if ((az group exists --name 'rg-platform-monitoring-${{ parameters.environment }}-uksouth') -eq $true) { 
                  Write-Host "Performing az deployment group validation as 'rg-platform-monitoring-${{ parameters.environment }}-uksouth' exists"
                  az deployment group validate `
                    --resource-group 'rg-platform-monitoring-${{ parameters.environment }}-uksouth' `
                    --template-file $(Build.sourcesDirectory)/bicep/services.bicep `
                    --parameters @$(Build.sourcesDirectory)/params/services.${{ parameters.environment }}.json
                }

          - task: AzureCLI@2
            name: RunWhatIfDeploy
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub what-if `
                  --template-file bicep/platform.bicep `
                  --location 'uksouth' `
                  --parameters @params/platform.${{ parameters.environment }}.json

                if ((az group what-if --name 'rg-platform-monitoring-${{ parameters.environment }}-uksouth') -eq $true) { 
                  Write-Host "Performing az deployment group validation as 'rg-platform-monitoring-${{ parameters.environment }}-uksouth' exists"
                  az deployment group validate `
                    --resource-group 'rg-platform-monitoring-${{ parameters.environment }}-uksouth' `
                    --template-file $(Build.sourcesDirectory)/bicep/services.bicep `
                    --parameters @$(Build.sourcesDirectory)/params/services.${{ parameters.environment }}.json
                }
